language: c

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_script:
  - wget http://www.nasm.us/pub/nasm/releasebuilds/2.11.08/nasm-2.11.08.tar.gz
  - tar xvf nasm-2.11.08.tar.gz
  - cd nasm-2.11.08
  - ./configure
  - make
  - export PATH=$PATH:$PWD
  - cd ..
  - wget http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
  - tar xvf yasm-1.3.0.tar.gz
  - cd yasm-1.3.0
  - ./configure
  - make
  - export PATH=$PATH:$PWD
  - cd ..
  - nasm -v
  - yasm --version

script:
  - export CXX=g++-4.8 CC=gcc-4.8
  - autoreconf -iv
  - ./configure
  - make
  - ./src/bin/hevcasm

